/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.vmi.mapmatching_demo;

public final class R {
    public static final class array {
        public static final int tileset_array=0x7f060000;
    }
    public static final class attr {
    }
    public static final class dimen {
        public static final int padding_large=0x7f040002;
        public static final int padding_medium=0x7f040001;
        public static final int padding_small=0x7f040000;
    }
    public static final class drawable {
        public static final int ic_action_search=0x7f020000;
        public static final int ic_launcher=0x7f020001;
        public static final int marker_green=0x7f020002;
        public static final int marker_red=0x7f020003;
    }
    public static final class id {
        public static final int apply_general_settings=0x7f09000b;
        public static final int apply_new_settings=0x7f090007;
        public static final int clear_button_lines=0x7f090002;
        public static final int clear_button_points=0x7f090001;
        public static final int edit_address=0x7f090003;
        public static final int edit_database_name=0x7f090004;
        public static final int edit_password=0x7f090006;
        public static final int edit_sampling_rate=0x7f090009;
        public static final int edit_username=0x7f090005;
        public static final int menu_settings=0x7f09000c;
        public static final int placeholder1=0x7f09000e;
        public static final int publicTransportMapView=0x7f090000;
        public static final int quit=0x7f09000f;
        public static final int set_range_query_radius=0x7f09000a;
        public static final int settings=0x7f09000d;
        public static final int tileset_spinner=0x7f090008;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int psql_settings=0x7f030001;
        public static final int settings=0x7f030002;
    }
    public static final class menu {
        public static final int activity_main=0x7f080000;
        public static final int menu=0x7f080001;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int menu_settings=0x7f050001;
        public static final int title_activity_main=0x7f050002;
    }
    public static final class style {
        public static final int AppTheme=0x7f070000;
    }
}
